### PR TITLE
Toxic Spill data based on Jack's DB

### PR DESCRIPTION
**Pull request by groupsky**
Extracted for both RRB and MRRB with separation for Rotten/Super Rotten and without. MRRB doesn't have enough data with rotten/super rotten, so it's not included in data. 

Ref #79

### CODE REVIEW

**Comment by tsitu** [comment]
Hi Geno, looks like Jack's sample sizes are still insufficient across the board, except for perhaps Count and up + regular Rancid Radioactive Blue. As such, I can't tell if the differences in population distribution are due to SSSS (small sample size syndrome) or actual changes since the location became permanent.

What do you think about combining the existing HT data with these newer numbers? The existing `populations.csv` data is about 2 years old so there shouldn't be any overlap.

**Comment by groupsky** [comment]
Haven't really checked the population difference, but if you feel it might be off, I'm ok with combining the populations. 

What sample size would you say it enough? I can make a new export filtering any setup with less sample.

**Comment by tsitu** [comment]
Low sample size from Jack's data wouldn't matter if we combined it with HT's. I think this is the best solution for the time being, at least until we can reach sufficient accuracy using Jack's data alone.

I've posted on Discord, MH Forums, and Facebook asking folks to help find a formula to determine the sample size required for ~95% accuracy for a location/phase/cheese setup with _n_ number of mice in its attraction pool. For example, Hero/RRB with its 6 mice probably requires a smaller sample size for its percentages to be reasonably accurate than Archduke/RRB with its 14 mice.

**Comment by tsitu** [comment]
@groupsky 

Screenshot of the Sample Size Report for this population update: https://i.imgur.com/dY5s5gn.png (build #188 on Travis)

The location score should be at least 15.00 (currently 5.51) before I can apply the changes. I'd rather let Jack's data catch up to this threshold than combine it with HT's.

**Comment by tsitu** [comment]
Made an updated extraction in #90 so I'll be closing this PR. Sample size data still isn't optimal, but it's halfway decent for the more popular stages. Thanks for opening 👍

**Pull request closed without merging**
