### PR TITLE
WWRift Population Update

### PR DESCRIPTION
**Pull request by bavovanachte**
Hi, I was playing around with the MHCT database and figured I'd try to contribute to issue https://github.com/tsitu/MH-Tools/issues/79 while I'm at it. 

As you can see, this is not finished yet (I've only done Low/Low/Low and Medium/Low/Low). I wanted to check first if the approach is the right one (for now there isn't a separate csv for wwrift yet, I don't know how the original data was generated?), as the process is fairly time-consuming

### CODE REVIEW

**Comment by bavovanachte** [comment]
As this approach seems to render sensible results, I went ahead and added the phases that are currently supported by the CRE. 

The "Monstrous Black Widow" phase confuses me a bit, though. What is this based on?

**Comment by bavovanachte** [comment]
Would you like me to close this MR? I'd be equally happy keeping them on my fork if they're not ok.

I'd still like to know what the "Monstrous Black Widow" phase is based on, though 😄

**Comment by tsitu** [comment]
Sorry about the delayed response on this PR - I've been preoccupied recently with various Valour Rift, Halloween, and RH Season 7 stuff. I really do appreciate it though! You've done a much better job than me programatically fetching all of the different stages.

To answer your question, the existing data was manually curated by another contributor several years ago. She tweaked a bunch of filters on HornTracker to make it happen, with some stages deliberately left out due to insufficient sample sizes. As I remember it, "Monstrous Black Widow" was a broad query for the point at which MBW started to appear in populations. My guess is that it means every faction is between 25-49 rage, but I'm not too sure at this point, which means it's definitely worth revising.

As for some feedback:

- No need to include Taunting Charm in High/High/High stages. That particular column is for population-altering charms (e.g. Rotten Charms in Toxic Spill or Supply Schedule Charms in GES)
- Sample sizes are still mediocre in many stages, and in some cases have much lower sample sizes than HT (although one could argue that Jack's DB is more accurate). This tends to be the case in locations with a large number of distinct stage permutations (Fiery Warpath is another one that comes to mind). With that said, it would be really cool if a rough pattern could be derived with regards to rage levels + charms and their effects on ARs. If that proves too tricky I'll look to merge this in once the [location score](https://travis-ci.com/tsitu/MH-Tools/builds/136470110#L569) reaches 15 or so.

**Comment by bavovanachte** [comment]
> No need to include Taunting Charm in High/High/High stages

Good point. I initially included it to test if it made a difference in population and then forgot to remove it

>  it would be really cool if a rough pattern could be derived with regards to rage levels + charms and their effects on AR

That would be nice indeed! I tried to do some first analysis but got confused quickly by all the combinations. I'll try again when I have more time to spend on it

>  I'll look to merge this in once the location score reaches 15 or so.

Ok for me. If I find the time, I'll prepare a comparison between the current AR numbers and the new ones to see what the deviations

**Comment by hymccord** [comment]
This one can be closed due to #296

**Pull request closed without merging**
