### PR TITLE
Added the new items introduced during Ronza 2021

### PR DESCRIPTION
**Pull request by w0en**
Four items were added:
1) Chrome School of Sharks (Trap)
2) Cloaking Droid Trap (Trap)
3) Iceberg Boiler Base (Base)
4) Brilliant Water Jet Charm (Charm)

Relevant News post: https://www.mousehuntgame.com/newspost.php?news_post_id=560

Special effects of the base in Iceberg are not implemented in this PR.

### CODE REVIEW

**Comment by josephks** [comment]
For the Iceberg base see https://github.com/tsitu/MH-Tools/blob/master/src/main/cre.js#L483 .  It looks like you just have to add the new base to all the or statements that include `baseName === "Ultimate Iceberg Base"`

**Comment by tsitu** [comment]
Thanks to both of you for the help! 🎉

**Comment by josephks** [comment]
My CRE button isn't working.  I think it is because it is trying to find "Chrome School of Sharks Trap" instead of "Chrome School of Sharks"

**Comment by josephks** [comment]
If you look at your inventory some trap names have "Trap" and the end and some don't.  The Chrome SoS does have "Trap" and the end of the name.

**Pull request merged**
