### PR TITLE
Halloween 2017 Ghastly Galleon Gouda population retrieve from HornTracker

### PR DESCRIPTION
**Pull request by groupsky**
This is a very rough script that fetches the population of event mice from HT and outputs in the population.csv format.

To test it you need to install the dependencies `npm install` and then manually run `node tools/hw17pop.js`. The output could be directly piped to the populations.csv file and works for the mapper tool. CRE and Setup tools needs mouse powers, which are missing, so currently they don't work.

Haven't figured a proper way to update the population data, one way could be to use separate file which gets merged with the base one during the build process. I'm open for suggestions.

### CODE REVIEW

**Comment by groupsky** [comment]
Updated so now Halloween population is a separate file and get's included when building the populations

**Comment by groupsky** [comment]
I made it temporary available on [my fork](https://groupsky.github.io/MH-Tools/map.html) for anyone wanting to try it out.

Be warned that samples are still small - especially for Slushy only 95 hunts are available.

**Comment by Babalela01** [comment]
Usually we do not include event mice due to small sample sizes and them changing every year. 

@tsitu What do you think?

**Comment by groupsky** [comment]
On a second thought it may be better to leave the event population out of the tools. I can keep it up-to-date for the duration of the event, and then take it down.

In any case, I made a separate branch and some improvements on the tooling, so I'll close this PR. If you decide it's ok to merge it and keep it updated, let me know and I'll open a new PR.

**Comment by tsitu** [comment]
It would be great if the tools could support Halloween + every other event, but their mechanics, locations, and attraction rates change every year. This makes it infeasible to keep up with them and results in sample sizes with (relatively low) upper bounds.

With that said, I think your script to fetch from HT is the key takeaway here. The API seems to be a more reliable way to access Nick's DB than the web interface, so an automated way to validate existing population data or fetch new locations would be amazing. Wrote a [shell script](https://gist.github.com/tsitu/7262e4fd2170405e6dfd399df565cefc) last year in an attempt to do this, but things got complicated when including phases, special charms, etc.

**Comment by groupsky** [comment]
> It would be great if the tools could support Halloween + every other event, but their mechanics, locations, and attraction rates change every year. This makes it infeasible to keep up with them and results in sample sizes with (relatively low) upper bounds.

To keep up with the events it does require some effort, but I believe with proper tooling that effort could be minimized. Personally I tend to run several queries on HT in the beginning of events to get a feeling of population. These queries are of course specific for the event, but if we have the tools to write them as easy as in the web and then apply the CRE/Setup/Map tools on top of the result, that should be helpful to a lot of users.

As far as the sample sizes - 2 days into the event and there are already over 10k recorded hunts. They tend to be focused on small subset of the locations, but even with 200 hunts per setup it is still helpful to get some rough idea about the population. I think if we emphasize the strength of the sample - similar to the CRE notice - that should give enough context to people.

I think there is also the problem of handling such rapid updates. Getting a lot of changes in a short timeframe is stressful enough, so this could be a good opportunity to figure out a safe way to support it.

> I think your script to fetch from HT is the key takeaway here.

I was thinking about making a separate PR for that. Will probably do one tomorrow.

> The API seems to be a more reliable way to access Nick's DB than the web interface

Wow, never knew there was an API :smile:. Gotta check it out. Do you have some link with doc or anything?

> Wrote a shell script last year in an attempt to do this, but things got complicated when including phases, special charms, etc.

My vision is that the base tool should not be aware of that, as I've implemented it currently it's a simple wrapper over the requesting/parsing and it's up to more specialized tools to know what exactly should be queried. I'm still figuring out the best way to do it - can see the [MoPi tool](https://github.com/groupsky/MH-Tools/blob/mopi/tools/mopipop.js)

**Comment by tsitu** [comment]
Sorry for the late reply on this. Just wanted to agree with your point that proper tooling would minimize the effort to add event data, but again, timing is often an issue. Some major events like Lunar New Year and Valentine's simply don't last long enough for meaningful sample sizes to be recorded or for new mouse powers/effectiveness values to be calculated.

However, longer events that take place within a single unique location like GWH and MH's Birthday are much more feasible. To prevent bogging down permanent locations, we might have to separate views for event data, either by toggling some sort of checkbox on CRE/Setup/Map or creating new pages like EventCRE/EventMap/EventSetup.

> Wow, never knew there was an API 😄. Gotta check it out. Do you have some link with doc or anything?

The link is [here](https://docs.google.com/document/d/1eyPoJMBgDXqiM3c_8Ocq7BMiydpYRj2PkdtFEU6affY/edit), but it's not very well documented 😃

**Pull request closed without merging**
