### PR TITLE
Display loot drops in CRE tool

### PR DESCRIPTION
**Pull request by groupsky**
This is implementation of the idea commented in #54.

Locations without specific loot:

  * [ ] Gnawnia
  * [ ] Toxic Spill
  * [ ] Sunken City

Currently live at https://groupsky.github.io/MH-Tools/cre.html

### CODE REVIEW

**Comment by groupsky** [comment]
I'm afraid I broke the horn tracker while extracting the data for all locations, so I'll migrate to jack's tools for the rest of the data.

**Comment by groupsky** [comment]
@tsitu I have almost complete data now, sadly the horntracker broke down so I had to resort to jack's db for some of the data. Currently jack's data is not enough for sunken city - not enough data and no support for the zones.

As to your request to have only primary loot visible - I'm thinking of adding a field in the data, and use it to filter the displayed items. Not sure how quick I can do it, so I may resort to adding a simple toggle for show/hide all loot data.

Current data is deployed at [my fork](https://groupsky.github.io/MH-Tools/cre.html)

**Comment by groupsky** [comment]
Status update: turns out I was using a month old dump of Jack's database, so I need to reextact data from latest dump. This will likely happen next week.

Another concern I have is about the loot - I feel I didn't do very good job at selecting/filtering the right items, so I could use some feedback on this. A simple list per location would be enough.

Final concern is that some of the extractors are use specific requests to horntracker, and as ht is continuing to be down, maybe I need to convert them to extract from jack's db, but that is lacking on some of the old locations.

**Comment by tsitu** [comment]
Apologies for the extremely late response on this. 🤕 

- HornTracker has been back online for some time now. Do you still plan on using a mix of data from both HT and Jack's DB?
- Are there specific locations where your selected items don't seem optimal? If there are many, I can try to outsource the validation to Discord/MH forums.
- IMO the CRE results table currently looks too tall and wide on your fork. Would it be useful to add checkboxes to show/hide the tourney points / loot / rank columns?

**Comment by groupsky** [comment]
> * HornTracker has been back online for some time now. Do you still plan on using a mix of data from both HT and Jack's DB?

Recently I tried to run some extractions based on HT for SC and couldn't get any data out of it. So I don't think I'll keep on trying. For the past several months I've been using mostly Jack's data to extract and feel much more confident with that. I'm slowly adding better stage reporting to Jack's tool so it should be able to provide all necessary data in some time in the future. For now I'm more or less satisfied with the quality and coverage of data I managed to extract.

> * Are there specific locations where your selected items don't seem optimal? If there are many, I can try to outsource the validation to Discord/MH forums.

If I had any particular I would ask or just fix. I think when people start using it they should open tickets for missing/wrong items and gradually things will get better.

> * IMO the CRE results table currently looks too tall and wide on your fork. Would it be useful to add checkboxes to show/hide the tourney points / loot / rank columns?

I don't like the current visualization too, but I don't have a lot of time to tinker with it. I think it would be best if the whole table display is refactored, so we first prepare an array with the data, and then just render the table, but that should go into a separate PR.

This PR took a lot of time and I'm little hesitant to work on it anymore. Let's prepare a short checklist what is needed to get it into master, and I'll try to complete it in next few days, or just drop it.

**Comment by tsitu** [comment]
> For now I'm more or less satisfied with the quality and coverage of data I managed to extract... I think when people start using it they should open tickets for missing/wrong items and gradually things will get better.

Agreed, haven't noticed any glaring omissions or extraneous inclusions in the data.

> I don't like the current visualization too, but I don't have a lot of time to tinker with it... This PR took a lot of time and I'm little hesitant to work on it anymore.

Totally understandable. I really appreciate your work on this PR and will try to pick up where you left off on it. Refactoring the table display render might not be necessary (for now) if we use tablesorter's [column selector widget](https://mottie.github.io/tablesorter/docs/example-widget-column-selector.html) to provide customization. I'll fiddle around with this over the next couple of days.

**Comment by groupsky** [comment]
I'll see to rebase on the latest master.

**Comment by groupsky** [comment]
Closing stale PR

**Pull request closed without merging**
