### PR TITLE
Update BWRift population and support paladin's bane buff

### PR DESCRIPTION
**Pull request by groupsky**
Antiskele population is computed from general population with removed Skeletal Champion.
Paladin's Bane population is computed from general population with removed Portal Paladin.

CRE bookmarklet is updated to support PB population phase.

Data is extracted from Sat Feb 3 07:56:28 2018 +0000 nightly backup

### CODE REVIEW

**Comment by tsitu** [comment]
The data looks solid, but I have a couple of minor concerns:

- No Portal Pursuer data even in locations where its AR is non-trivial (Ingress & Pursuer Mousoleum)
- Sample sizes for Rift Antiskele and Paladin's Bane seem like they shouldn't be strictly greater than "-" or equal to 'No Buff', respectively

**Comment by groupsky** [comment]
> No Portal Pursuer data even in locations where its AR is non-trivial (Ingress & Pursuer Mousoleum)

Good spot. I removed all pursuer populations without thinking about those two chambers, because the pursuer is usually available only with pursuer curse and that's a small subset of the sample data, and no way to distinguish. I'll rework the extraction to enable pursuer for Ingres and Pursuer Mousoleum.

> Sample sizes for Rift Antiskele and Paladin's Bane seem like they shouldn't be strictly greater than "-" or equal to 'No Buff', respectively

My logic is that antiskele and paladin's bane affect only the 2 mice from population, so instead of using the data only with charm (and for the buff there is no way to filter), I recalculate the population by artificially removing the respective mice. That also increases the sample size, because for normal population (not using Rift Antiskele) I exclude the hunts with the charm to get proper population, while for the charm population I can use all records no matter what charm. Let me know if you think this skews the data in some way.

**Comment by groupsky** [comment]
Fixed the extraction for Entrance, Guard Barracks, Ingress, Pursuer Mousoleum and Security.

One strange thing I noticed is there are no Paladins in Ingress or Pursuer Mousoleum, although the [wiki mentions](http://mhwiki.hitgrab.com/wiki/index.php/Bristle_Woods_Rift#Mice_6) them.

**Comment by tsitu** [comment]
> One strange thing I noticed is there are no Paladins in Ingress or Pursuer Mousoleum

Is it possible everyone so far has had Paladin's Bane buff on before entering those 2 chambers? I could try entering Ingress without buffs on my next run to see if they show up on the TEM.

> Let me know if you think this skews the data in some way.

1. From what I understand, the current `"Rift Antiskele"` populations include _every_ charm, while the `"-"` populations include every charm _except_ Rift Antiskele, which is why the former's sample sizes are larger. I'm just not sure whether a population with _only_ Rift Antiskele (i.e. sample size = `"Rift Antiskele"` - `"-"`) would end up having the same distribution of ARs as a population with every charm included.

2. Shouldn't artificially removing Portal Paladins decrease that particular sample size by however many Paladins were in the original sample? For example, if you filter out 5 Paladins (5.00%) from an original sample of 100, shouldn't the corresponding `"(Paladin's Bane)"` sample size be 95 instead of 100?

**Comment by groupsky** [comment]
> I'm just not sure whether a population with only Rift Antiskele (i.e. sample size = "Rift Antiskele" - "-") would end up having the same distribution of ARs as a population with every charm included.

This is a diff every charm versus rift antiskele for the two chambers with biggest sample. The differences are not huge and general distribution seems the same. I can of course switch to using the smaller sample but for the paladin buff there is currently no way (I submitted PR so soon data with buffs will start to show up) to separate the data.
```diff
-"Bristle Woods Rift","Acolyte","Runic String","Rift Antiskele","31.12%","Dread Knight",55157
+"Bristle Woods Rift","Acolyte","Runic String","Rift Antiskele","31.79%","Dread Knight",3660
-"Bristle Woods Rift","Acolyte","Runic String","Rift Antiskele","12.15%","Vigilant Ward",55157
+"Bristle Woods Rift","Acolyte","Runic String","Rift Antiskele","13.10%","Vigilant Ward",3660
-"Bristle Woods Rift","Acolyte","Runic String","Rift Antiskele","10.50%","Absolute Acolyte",55157
+"Bristle Woods Rift","Acolyte","Runic String","Rift Antiskele","9.43%","Absolute Acolyte",3660
-"Bristle Woods Rift","Acolyte","Runic String","Rift Antiskele","10.08%","Portal Paladin",55157
+"Bristle Woods Rift","Acolyte","Runic String","Rift Antiskele","9.18%","Timelost Thaumaturge",3660
-"Bristle Woods Rift","Acolyte","Runic String","Rift Antiskele","8.43%","Timelost Thaumaturge",55157
+"Bristle Woods Rift","Acolyte","Runic String","Rift Antiskele","8.00%","Shackled Servant",3660
-"Bristle Woods Rift","Acolyte","Runic String","Rift Antiskele","7.19%","Timeslither Pythoness",55157
+"Bristle Woods Rift","Acolyte","Runic String","Rift Antiskele","7.78%","Portal Paladin",3660
-"Bristle Woods Rift","Acolyte","Runic String","Rift Antiskele","7.14%","Shackled Servant",55157
+"Bristle Woods Rift","Acolyte","Runic String","Rift Antiskele","7.43%","Timeslither Pythoness",3660
-"Bristle Woods Rift","Acolyte","Runic String","Rift Antiskele","4.89%","Harbinger of Death",55157
+"Bristle Woods Rift","Acolyte","Runic String","Rift Antiskele","5.12%","Harbinger of Death",3660
-"Bristle Woods Rift","Acolyte","Runic String","Rift Antiskele","4.84%","Carrion Medium",55157
+"Bristle Woods Rift","Acolyte","Runic String","Rift Antiskele","5.10%","Carrion Medium",3660
-"Bristle Woods Rift","Acolyte","Runic String","Rift Antiskele","3.02%","Timeless Lich",55157
+"Bristle Woods Rift","Acolyte","Runic String","Rift Antiskele","2.52%","Timeless Lich",3660
-"Bristle Woods Rift","Acolyte","Runic String","Rift Antiskele","0.64%","Chronomaster",55157
+"Bristle Woods Rift","Acolyte","Runic String","Rift Antiskele","0.55%","Chronomaster",3660
-"Bristle Woods Rift","Timewarp","Runic String","Rift Antiskele","35.77%","Carrion Medium",43160
+"Bristle Woods Rift","Timewarp","Runic String","Rift Antiskele","35.42%","Carrion Medium",4521
-"Bristle Woods Rift","Timewarp","Runic String","Rift Antiskele","27.71%","Chronomaster",43160
+"Bristle Woods Rift","Timewarp","Runic String","Rift Antiskele","27.42%","Chronomaster",4521
-"Bristle Woods Rift","Timewarp","Runic String","Rift Antiskele","20.18%","Timeless Lich",43160
+"Bristle Woods Rift","Timewarp","Runic String","Rift Antiskele","20.12%","Timeless Lich",4521
-"Bristle Woods Rift","Timewarp","Runic String","Rift Antiskele","10.92%","Sentient Slime",43160
+"Bristle Woods Rift","Timewarp","Runic String","Rift Antiskele","11.66%","Sentient Slime",4521
-"Bristle Woods Rift","Timewarp","Runic String","Rift Antiskele","5.42%","Portal Paladin",43160
+"Bristle Woods Rift","Timewarp","Runic String","Rift Antiskele","5.39%","Portal Paladin",4521
```

> Shouldn't artificially removing Portal Paladins decrease that particular sample size by however many Paladins were in the original sample?

This is actually not accounted for when computing the sample size. It is currently the count of records initially selected from the db, any consecutive transformation is not accounted for. If you insist I can correct the sample size, but that shouldn't give any practical difference.

**Comment by tsitu** [comment]
I see some small discrepancies in the middle of the Acolyte/Runic String diff, but the Timewarp one is convincing enough in terms of distribution similarity. If you're satisfied with the PR I will go ahead and merge it.

**Pull request merged**
