### PR TITLE
Changed "Pawn Pincher" to "Pawn" for ZT phases

### PR DESCRIPTION
**Pull request by AardWolf**

### CODE REVIEW

**Review by eraymitrani — APPROVED** [review]

**Comment by tsitu** [comment]
Zugzwang's Tower attraction pools are already quite gnarly. This case is especially weird because each side's Pincher both increases the AR of its respective Pawn and decreases the AR of its opposite Pawn. So the AR numbers for this phase are specifically for when you have Pinchers armed (similar to Iceberg having distinct phases for Magnet Base, UIB, etc)

Therefore I don't think this quick fix really solves much - what we should look into is a robust and thorough ZT population extraction solution using MHCT.

**Comment by eraymitrani** [comment]
I thought this is just changing how the phase is named. Are there special cases for which population numbers are used based on the phase name elsewhere?

**Comment by tsitu** [comment]
> I thought this is just changing how the phase is named.

Yes, and I believe this change makes the phase name less accurate, since the current AR numbers are based on Pawn Pinchers being armed.

> Are there special cases for which population numbers are used based on the phase name elsewhere?

It's pretty rare, but I cited Iceberg above (Magnet, Remote Detonator, Hearthstone, and Ultimate Iceberg bases). Bristle Woods Rift is another example - it has phases for Paladin's Bane and Pursued, which makes things quite messy.

**Comment by AardWolf** [comment]
tsitu is correct, the stage is named properly compared to the ARs in the files. We would need to extract an additional stage for a generic "pawn" calculation.

But I am not sure the "pawn pincher" stages are themselves correct since pawn pincher could be armed at any time. And ZT stages are ugly because you also need to know what is unlocked on the other side. I think the most proper fix is to determine how the attraction weighting is done and mimic that.

**Comment by AardWolf** [comment]
Closing this as irrelevant. It needs to include different AR pools or a rework of ZT and it's crazy ARs.

**Pull request closed without merging**
