### PR TITLE
Update bm-loader.js for local use

### PR DESCRIPTION
**Pull request by DevJackSmith**
Adding local storage bypass

### CODE REVIEW

**Comment by DevJackSmith** [comment]
didn't test yet, just idea

**Comment by tsitu** [comment]
I don't really get the motivation for this change. Is it related to the idea you brought up on #community-tools?

**Comment by DevJackSmith** [comment]
yes, it allows you not to maintain two versions, but at the same time it allows me not to break extension rules

**Comment by DevJackSmith** [comment]
so this check would be added in all the bookmarklets, and then I can set the localMenuUrl, localCREUrl, localSetupUrl, etc before calling your extension, that way it will load all of those from code stored in my extension instead of remote. All three Opera, FF, Chrome have that in the rules clearly stated:
image

**Comment by tsitu** [comment]
Ok so you'd set the local bookmarklet URLs in your extension and pull latest copies on every build/release? `bm-menu` will need logic for this too as it uses the same cached SHA to fetch external JS.

**Comment by DevJackSmith** [comment]
correct. Here's the one i found about chrome: 
image

**Comment by DevJackSmith** [comment]
I still need to test this somehow, not sure yet how. Is there a way to produce minimized version of this so i can drop it into my extension and see if it works before merging into master?

**Comment by DevJackSmith** [comment]
for now i believe i fetch your minimized versions and put them in the extension zip, in a folder, where I point the autoloader to i think?. Anyway i don't think we need this PR for now. (Reading your comment above, is what i think we are doing now.) Might want to fetch your unminimized versions at some point if they complain.

**Pull request closed without merging**
